-- Report questions for AIScore pipeline.
-- Generated by GPT-4o from answered interview + company data,
-- used as scoring criteria for the final AIScore report.

ALTER TABLE customer_applications
    ADD COLUMN IF NOT EXISTS report_questions        JSONB,
    ADD COLUMN IF NOT EXISTS report_questions_status TEXT NOT NULL DEFAULT 'not_started';

-- report_questions_status values: 'not_started' | 'generating' | 'done' | 'error'
-- report_questions is a JSON array:
--   [{"id": "rq_1", "category": "...", "question": "...", "scoring_guide": "..."}, ...]
